name: Build and Deploy Docker Image to dev_EC2

on:
  push:
    branches:
      - main

jobs:
  deploy_dev:
    name: Build and Deploy to Dev
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image with secrets as build args
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
          NEXT_PUBLIC_AES_KEY: ${{ secrets.NEXT_PUBLIC_AES_KEY }}
        run: |
          echo ${{ secrets.DOCKER_SECRET }} | docker login -u neon20 --password-stdin


          # Build the Docker image with build arguments
          docker build \
            --build-arg NEXT_PUBLIC_AES_KEY=${NEXT_PUBLIC_AES_KEY} \
            -t my-nextjs-app .
          docker tag my-nextjs-app:latest neon20/flitchpay:latest
          docker push neon20/flitchpay:latest

      - name: Deploy to Dev using SSH
        env:
          AWS_EC2_PEM: ${{ secrets.AWS_EC2_DEV_PEM }}
          AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_DEV_PUBLIC_IP }}
          AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_DEV_USERNAME }}
        run: |
          echo "$AWS_EC2_PEM" > private.pem && chmod 600 private.pem

          cat << 'EOF' > deploy_script.sh
           #!/bin/bash
           sudo docker stop nextjs || true
           sudo docker rm nextjs || true
           sudo docker pull neon20/flitchpay
           sudo docker run -d --name nextjs -p 3000:3000 neon20/flitchpay
          EOF

          scp -o StrictHostKeyChecking=no -i private.pem deploy_script.sh ${AWS_EC2_USERNAME}@${AWS_EC2_PUBLIC_IP}:~/deploy_script.sh
          ssh -o StrictHostKeyChecking=no -i private.pem ${AWS_EC2_USERNAME}@${AWS_EC2_PUBLIC_IP} 'chmod +x ~/deploy_script.sh && ~/deploy_script.sh'
